In [92]:
import pandas as pd
from sqlalchemy import create_engine

engine = create_engine('postgresql+psycopg2://user:admin@localhost:5432/nba_stats')

In [109]:
df_anthro_orig = pd.read_sql_table('ANTHRO_FEAT', con=engine)
df_physical_orig = pd.read_sql_table('PHYSICAL_FEAT', con=engine)
df_shots_orig = pd.read_sql_table('SHOTS', con=engine)
df_events_orig = pd.read_sql_table('EVENTS', con=engine)

In [110]:
print(len(df_shots_orig["PLAYER_NAME"].unique()))
print(len(df_anthro_orig["PLAYER"].unique()))
print(len(df_physical_orig["PLAYER"].unique()))
print(len(df_events_orig["PLAYER1_NAME"].unique()))

2164
1367
1367
670

In [95]:

nba_teams = {
    'Los Angeles Lakers': 'LAL',
    'Oklahoma City Thunder': 'OKC',
    'Phoenix Suns': 'PHX',
    'Indiana Pacers': 'IND',
    'Utah Jazz': 'UTA',
    'Memphis Grizzlies': 'MEM',
    'Portland Trail Blazers': 'POR',
    'Detroit Pistons': 'DET',
    'New York Knicks': 'NYK',
    'LA Clippers': 'LAC',
    'Denver Nuggets': 'DEN',
    'Cleveland Cavaliers': 'CLE',
    'Chicago Bulls': 'CHI',
    'Boston Celtics': 'BOS',
    'Charlotte Hornets': 'CHA',
    'Dallas Mavericks': 'DAL',
    'Milwaukee Bucks': 'MIL',
    'Miami Heat': 'MIA',
    'New Orleans Pelicans': 'NOP',
    'San Antonio Spurs': 'SAS',
    'Toronto Raptors': 'TOR',
    'Atlanta Hawks': 'ATL',
    'Golden State Warriors': 'GSW',
    'Minnesota Timberwolves': 'MIN',
    'Sacramento Kings': 'SAC',
    'Orlando Magic': 'ORL',
    'Brooklyn Nets': 'BKN',
    'Houston Rockets': 'HOU',
    'Philadelphia 76ers': 'PHI',
    'Washington Wizards': 'WAS'
}

df_teams = df_shots_orig[['TEAM_ID', 'TEAM_NAME']].drop_duplicates().reset_index(drop=True)
df_teams['TEAM_ABBR'] = df_teams['TEAM_NAME'].map(nba_teams).astype('category')
df_teams

       TEAM_ID               TEAM_NAME TEAM_ABBR
0   1610612747      Los Angeles Lakers       LAL
1   1610612760   Oklahoma City Thunder       OKC
2   1610612756            Phoenix Suns       PHX
3   1610612754          Indiana Pacers       IND
4   1610612762               Utah Jazz       UTA
5   1610612763       Memphis Grizzlies       MEM
6   1610612757  Portland Trail Blazers       POR
7   1610612765         Detroit Pistons       DET
8   1610612752         New York Knicks       NYK
9   1610612746             LA Clippers       LAC
10  1610612743          Denver Nuggets       DEN
11  1610612739     Cleveland Cavaliers       CLE
12  1610612741           Chicago Bulls       CHI
13  1610612738          Boston Celtics       BOS
14  1610612766       Charlotte Hornets       CHA
15  1610612742        Dallas Mavericks       DAL
16  1610612749         Milwaukee Bucks       MIL
17  1610612748              Miami Heat       MIA
18  1610612740    New Orleans Pelicans       NOP
19  1610612759       San Antonio Spurs       SAS
20  1610612761         Toronto Raptors       TOR
21  1610612737           Atlanta Hawks       ATL
22  1610612744   Golden State Warriors       GSW
23  1610612750  Minnesota Timberwolves       MIN
24  1610612758        Sacramento Kings       SAC
25  1610612753           Orlando Magic       ORL
26  1610612751           Brooklyn Nets       BKN
27  1610612745         Houston Rockets       HOU
28  1610612755      Philadelphia 76ers       PHI
29  1610612764      Washington Wizards       WAS

In [103]:
# df_players = df_shots_orig[['PLAYER_ID', 'PLAYER_NAME']].drop_duplicates().reset_index(drop=True)
# df_players["PLAYER_ID"] = df_players["PLAYER_ID"].astype('category')
# df_players

df_players_events = df_events_orig[
    ['PLAYER1_ID', 'PLAYER1_NAME', "PLAYER2_ID", "PLAYER2_NAME"]].drop_duplicates().reset_index(drop=True)
df_players_events["PLAYER1_ID"] = df_players_events["PLAYER1_ID"].astype('category')
df_players_events["PLAYER2_ID"] = df_players_events["PLAYER2_ID"].astype('category')

df_players_events

      PLAYER1_ID        PLAYER1_NAME PLAYER2_ID        PLAYER2_NAME
0              0                None          0                None
1         203076       Anthony Davis    1626157  Karl-Anthony Towns
2            708       Kevin Garnett     201937         Ricky Rubio
3         203076       Anthony Davis     201569         Eric Gordon
4        1626157  Karl-Anthony Towns        708       Kevin Garnett
...          ...                 ...        ...                 ...
30926     203118          Mike Scott     201229    Anthony Tolliver
30927     201168      Tiago Splitter     101141      Ersan Ilyasova
30928        579                None          0                None
30929     203083      Andre Drummond     203145       Kent Bazemore
30930        597                None          0                None

[30931 rows x 4 columns]

In [107]:
df_events = df_events_orig.copy()
df_events.columns = ['GAME_ID', 'EVENTNUM', 'EVENTMSGTYPE', 'EVENTMSGACTIONTYPE', 'PERIOD',
                     'WCTIMESTRING', 'PCTIMESTRING', 'HOMEDESCRIPTION', 'NEUTRALDESCRIPTION',
                     'VISITORDESCRIPTION', 'SCORE', 'SCOREMARGIN', 'PERSON1TYPE',
                     'PLAYER1_ID', 'PLAYER1_NAME', 'PLAYER1_TEAM_ID', 'PLAYER1_TEAM_CITY',
                     'PLAYER1_TEAM_NICKNAME', 'PLAYER1_TEAM_ABBREVIATION', 'PERSON2TYPE',
                     'PLAYER2_ID', 'PLAYER2_NAME', 'PLAYER2_TEAM_ID', 'PLAYER2_TEAM_CITY',
                     'PLAYER2_TEAM_NICKNAME', 'PLAYER2_TEAM_ABBREVIATION', 'PERSON3TYPE',
                     'PLAYER3_ID', 'PLAYER3_NAME', 'PLAYER3_TEAM_ID', 'PLAYER3_TEAM_CITY',
                     'PLAYER3_TEAM_NICKNAME', 'PLAYER3_TEAM_ABBREVIATION']
df_events

,GAME_ID,EVENTNUM,EVENTMSGTYPE,EVENTMSGACTIONTYPE,PERIOD,WCTIMESTRING,PCTIMESTRING,HOMEDESCRIPTION,NEUTRALDESCRIPTION,VISITORDESCRIPTION,...,PLAYER2_TEAM_CITY,PLAYER2_TEAM_NICKNAME,PLAYER2_TEAM_ABBREVIATION,PERSON3TYPE,PLAYER3_ID,PLAYER3_NAME,PLAYER3_TEAM_ID,PLAYER3_TEAM_CITY,PLAYER3_TEAM_NICKNAME,PLAYER3_TEAM_ABBREVIATION
0,21500626,0,12,0,1,8:11 PM,12:00,None,NaN,None,...,None,None,None,0,0,None,NaN,None,None,None
1,21500626,1,10,0,1,8:11 PM,12:00,Jump Ball Davis vs. Towns: Tip to Garnett,NaN,None,...,Minnesota,Timberwolves,MIN,5,708,Kevin Garnett,1.610613e+09,Minnesota,Timberwolves,MIN
2,21500626,2,1,1,1,8:11 PM,11:40,None,NaN,Garnett 20' Jump Shot (2 PTS) (Rubio 1 AST),...,Minnesota,Timberwolves,MIN,0,0,None,NaN,None,None,None
3,21500626,4,1,42,1,8:11 PM,11:24,Davis 2' Driving Layup (2 PTS) (Gordon 1 AST),NaN,None,...,New Orleans,Pelicans,NOP,0,0,None,NaN,None,None,None
4,21500626,5,1,1,1,8:12 PM,11:10,None,NaN,Towns 24' 3PT Jump Shot (3 PTS) (Garnett 1 AST),...,Minnesota,Timberwolves,MIN,0,0,None,NaN,None,None,None
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
292449,21500429,595,2,1,4,10:30 PM,0:09,MISS Horford 19' Jump Shot,NaN,None,...,None,None,None,0,0,None,NaN,None,None,None
292450,21500429,596,4,0,4,10:30 PM,0:08,None,NaN,Jackson REBOUND (Off:1 Def:4),...,None,None,None,0,0,None,NaN,None,None,None
292451,21500429,597,1,1,4,10:30 PM,0:00,None,NaN,Marc Morris 24' 3PT Jump Shot (22 PTS) (Jackso...,...,Detroit,Pistons,DET,0,0,None,NaN,None,None,None
292452,21500429,598,18,0,4,10:30 PM,0:00,None,NaN,None,...,None,None,None,1,0,None,NaN,None,None,None
292453,21500429,599,13,0,4,10:30 PM,0:00,None,NaN,None,...,None,None,None,0,0,None,NaN,None,None,None

In [108]:
df_shots = df_shots_orig.copy()
df_shots["ACTION_TYPE_CAT"] = df_shots["ACTION_TYPE"].astype('category').cat.codes
df_shots["MADE_SHOT"] = df_shots["SHOT_MADE_FLAG"].astype('bool')
df_shots["IS_3PT"] = df_shots["SHOT_TYPE"].str.contains("3PT")
df_shots["HTM"] = df_shots["HTM"].astype('category')
df_shots["VTM"] = df_shots["VTM"].astype('category')

cols_to_drop = ["EVENT_TYPE", "GRID_TYPE", "PERIOD", "SHOT_ATTEMPTED_FLAG", "SHOT_MADE_FLAG", "SHOT_TYPE",
                "SHOT_ZONE_AREA", "SHOT_ZONE_BASIC", "SHOT_ZONE_RANGE", "TEAM_NAME", "TEAM_ID"]

df_shots = df_shots.drop(columns=cols_to_drop)

df_shots

,ACTION_TYPE,EVENTTIME,GAME_DATE,GAME_EVENT_ID,GAME_ID,HTM,LOC_X_CM,LOC_Y_CM,MINUTES_REMAINING,PLAYER_ID,PLAYER_NAME,QUARTER,SECONDS_REMAINING,SHOT_DISTANCE_CM,SHOT_TIME,VTM,ACTION_TYPE_CAT,MADE_SHOT,IS_3PT
0,Jump Shot,215,2015-12-23,93,21500435,LAL,-60.915550,399.025872,3,101138,Brandon Bass,1.0,35,457.20,218.50,OKC,24,False,False
1,Dunk Shot,191,2015-12-23,97,21500435,LAL,569.778134,63.414148,3,101138,Brandon Bass,1.0,11,0.00,204.83,OKC,16,True,False
2,Jump Shot,518,2015-12-23,164,21500435,LAL,-13.746988,439.572654,8,101138,Brandon Bass,2.0,38,487.68,520.65,OKC,24,True,False
3,Jump Shot,120,2015-12-23,382,21500435,LAL,-65.875154,403.242780,2,101138,Brandon Bass,3.0,0,457.20,123.26,OKC,24,False,False
4,Jump Shot,646,2015-12-23,14,21500435,LAL,452.970900,51.234848,10,201579,Roy Hibbert,1.0,46,457.20,650.49,OKC,24,True,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
84462,Driving Layup Shot,32,2015-12-16,109,21500377,CHI,183.477154,498.647466,0,201149,Joakim Noah,1.0,32,30.48,18.10,MEM,13,True,False
84463,Jump Shot,564,2015-12-16,16,21500377,CHI,-468.448644,35.682936,9,201188,Marc Gasol,1.0,24,548.64,567.02,MEM,24,False,False
84464,Jump Shot,538,2015-12-16,19,21500377,CHI,258.008628,393.111736,8,201188,Marc Gasol,1.0,58,548.64,541.59,MEM,24,False,False
84465,Jump Shot,486,2015-12-16,29,21500377,CHI,-234.591606,119.090948,8,201188,Marc Gasol,1.0,6,335.28,489.03,MEM,24,True,False
84466,Jump Shot,457,2015-12-16,31,21500377,CHI,524.021304,112.125760,7,201188,Marc Gasol,1.0,37,548.64,451.37,MEM,24,True,False